website:
  base_url: "https://the-internet.herokuapp.com"
  
login:
  - username: "tomsmith"
    password: "SuperSecretPassword!"

  - username: "wrongusername"
    password: "wrongpassword"

  - username: "tomsmith"
    password: "wrongpassword"

  - username: null
    password: null

timeouts:
  explicit_wait: 10
  implicit_wait: 5